name: Java CI with Maven

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Generate report
        run: mvn surefire-report:report
        continue-on-error: true
      - name: display files
        run: cat target/site/surefire-report.html
      - name: Create or Update Comment
        continue-on-error: true
        uses: peter-evans/create-or-update-comment@v2.1.0
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Issued by: `${{github.event.sender.login}}` on branch: `${{ github.event.pull_request.head.label }}`
            Tests report can be found in the next comment.
      - name: replace unused script
        continue-on-error: true
        run: |
          sed -i '/<script/,/script>/d' target/site/surefire-report.html
          sed -i 's/title/h1/g' target/site/surefire-report.html
      - name: Create or Update Comment
        continue-on-error: true
        uses: peter-evans/create-or-update-comment@v2.1.0
        with:
          issue-number: ${{ github.event.number }}
          body-file: 'target/site/surefire-report.html'
