name: Java CI with Maven

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Tests with Maven
        run: mvn -DtestSourceDirectory=src/test/java test
      - name: Generate report
        run: mvn surefire-report:report
      - name: display files
        run: cat target/site/surefire-report.html
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v2.1.0
        with:
          issue-number: ${{ github.event.number }}
          body: |
            ${{github.event.sender.login}} with  ${{ github.event.pull_request.head.label }}
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v2.1.0
        with:
          issue-number:  ${{ github.event.number }}
          body-file: 'target/site/surefire-report.html'
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
      - name: test get line number
        run: | 
            grep -Fwn '[INFO] Results:' log.txt | cut -d: -f1
      - name: Build with Maven
        run: mvn -B package --file pom.xml


