name: Package application

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - if: success()
        uses: peter-evans/create-or-update-comment@v2.1.0
        with:
          issue-number: ${{ github.event.number }}
          body: |
            ## Issued by: `${{github.event.sender.login}}` on branch: `${{ github.event.pull_request.head.label }}`.
            ### The `mvn package` run successfully.
      - if: failure()
        uses: peter-evans/create-or-update-comment@v2.1.0
        with:
          issue-number: ${{ github.event.number }}
          body: | 
            ## Issued by: `${{github.event.sender.login}}` on branch: `${{ github.event.pull_request.head.label }}`.
            ### The `mvn package` command failed. Please check the logs for more information
